# Generated by Django 3.2 on 2022-08-24 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_type', models.TextField(default='SQLite', max_length=64)),
                ('db_status', models.TextField(default='true', max_length=64)),
                ('db_name', models.TextField(max_length=64, null=True)),
                ('db_host', models.TextField(max_length=64, null=True)),
                ('db_port', models.TextField(max_length=64, null=True)),
                ('db_user', models.TextField(max_length=64, null=True)),
                ('db_password', models.TextField(max_length=64, null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
