# Generated by Django 3.2 on 2022-08-24 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('avatar', models.TextField(null=True)),
                ('user_type', models.TextField(default='member')),
                ('mobile', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='is_show_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platform',
            name='db_status',
            field=models.BooleanField(default=True),
        ),
    ]
