# Generated by Django 3.2 on 2022-08-28 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0002_auto_20220824_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkgname', models.CharField(max_length=64)),
                ('icon', models.TextField(null=True)),
                ('newest_version', models.TextField(null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='package_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkgname', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('platform', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=64)),
                ('is_share', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='普通用户'),
        ),
    ]
