# Generated by Django 3.2 on 2022-08-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0003_auto_20220828_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initialized',
            field=models.IntegerField(default=0),
        ),
    ]
