# Generated by Django 3.2 on 2022-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0004_user_initialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
