# Generated by Django 3.2 on 2022-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_info',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
