# Generated by Django 3.2 on 2022-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0007_package_info_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_info',
            name='creater',
            field=models.TextField(default='hyacinth'),
        ),
    ]
