# Generated by Django 3.2 on 2022-09-21 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0008_package_info_creater'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_share_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64)),
                ('pkgname', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('platform', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='package_list',
            name='build_num',
            field=models.IntegerField(default=0),
        ),
    ]
