# Generated by Django 3.2 on 2022-09-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0009_auto_20220921_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_list',
            name='filepath',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package_share_info',
            name='filepath',
            field=models.TextField(default=''),
        ),
    ]
