# Generated by Django 3.2 on 2022-09-21 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0010_auto_20220921_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_version_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pkgname', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
