# Generated by Django 4.1.1 on 2022-09-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hysite', '0012_package_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='package_log',
        ),
    ]
